name: Test Project 

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        # Keyword to use an Action
        uses: actions/checkout@v3
      # NOTE: Node is already installed in the runner
      - name: Install NodeJS
        uses: actions/setup-node@v3
        # Configuration for the Action
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test