name: 03 - Deploy Project 

# Allow multiple event triggers
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./03-basics/react-project
    steps:
      - name: Get code
        # Keyword to use an Action
        uses: actions/checkout@v3
      # NOTE: Node is already installed in the runner
      - name: Install NodeJS
        uses: actions/setup-node@v3
        # Configuration for the Action
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    # To run this job after the "test" job has finished
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./03-basics/react-project
    steps:
      - name: Get code
        # Keyword to use an Action
        uses: actions/checkout@v3
      # NOTE: Node is already installed in the runner
      - name: Install NodeJS
        uses: actions/setup-node@v3
        # Configuration for the Action
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."
