name: 04 - Events Demo 1
on:
  pull_request:
    # Define activity types that trigger this event
    types:
      - opened
    # Define filters to trigger this event when the PR targets to a specific set of branches
    branches:
      - main # main
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
  workflow_dispatch:
  push: 
    # Define filters to trigger this event when the code is pushed to a specific set of branches
    branches:
      - main # main
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
    paths-ignore:
      - '04-workflows/starting-project/.github/workflows/*'
jobs:
  output-data:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./04-workflows/starting-project
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."