name: 05 - Deploy website
on:
  push:
    branches:
      - main
    paths:
      - 05-artifacts/starting-project/*
      - .github/workflows/05-demo.yml
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./05-artifacts/starting-project
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: 05-artifacts/starting-project/~/.npm
          key: deps-node-modules-${{ hashFiles('05-artifacts/starting-project/**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      # Map the publish step output to be a job output
      script-file: ${{ steps.publish.outputs.script-file }}
    defaults:
      run:
        working-directory: ./05-artifacts/starting-project
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: 05-artifacts/starting-project/~/.npm
          key: deps-node-modules-${{ hashFiles('05-artifacts/starting-project/**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      # Generate a simple value output
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo '::set-output name=script-file::{}' ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: 05-artifacts/starting-project/dist
          # Example for adding multiple paths
          # path: |
          #   05-artifacts/starting-project/dist
          #   05-artifacts/starting-project/package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Ouput filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."
