name: 07 - Website Deployment (Continue)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 07-execution-flow/**
      - .github/workflows/07-execution-flow.yml
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./07-execution-flow/starting-project
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: 07-execution-flow/starting-project/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./07-execution-flow/starting-project
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: 07-execution-flow/starting-project/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test code
        # To reference this step in others steps
        id: run-tests
        run: npm run test
        # To continue executing next steps and jobs even if this step fails
        continue-on-error: true
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: 07-execution-flow/starting-project/test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./07-execution-flow/starting-project
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: 07-execution-flow/starting-project/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: 07-execution-flow/starting-project/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
  report:
    needs: [lint, deploy]
    # Condition at job level
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ toJson(github) }}"